### ISSUE TITLE
What do you mean about "crime" ?

### ISSUE THREAD

**Issue by MR-MKZ** [Amirali-Salari/Library_Management#1]
https://github.com/Amirali-Salari/Library_Management/blob/f82c4e57e258f6164b68e67459e0c039272d7038/controllers/usersController.js#L31

> [!NOTE]
> Crime meaning: جرم و جنایت

**Comment by Amirali-Salari** [comment]
Hello MR-MKZ.
Thanks for your contribution.
Actually, what I mean by "setCrime" is to set a penalty for users who are late in delivering books.
But I chose a wrong keyword.
Therefore, all "Crime" variables were changed to "Fine".
_This issue was fixed in commit a31d9aa_
